### ISSUE TITLE
设备语言显示

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/BASE#1]
app内语言不会全部跟随系统语言，还存在中文（按键）；图标会压到文字（温湿度计）
![63F07541D5A2D17CE9244357DE5EA5F8](https://user-images.githubusercontent.com/52404201/69026426-c2f26080-0a05-11ea-98ca-36ca00b515c6.png)
APP版本：2.04

**Comment by tracyhenryduck2** [comment]
已解决@fengzehua5

**Comment by fengzehua5** [comment]
已验证
