### ISSUE TITLE
关于页的修改

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/BASE#14]
关于页的一些修改，见下图 @tracyhenryduck2 
![1576725909714](https://user-images.githubusercontent.com/52404201/71154150-d1869e80-2275-11ea-897b-a52fc09003d2.png)

**Comment by tracyhenryduck2** [comment]
@fengzehua5 android和ios都要改吗？

**Comment by tracyhenryduck2** [comment]
@javofxu

**Comment by fengzehua5** [comment]
已解决
