### ISSUE TITLE
插座显示问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/BASE#2]
插座设备页里的“Socket ON&OFF”应该跟随系统语言，插座关闭时为红色，对应文字应为“Socket OFF”
![6427A7A34E90596E03D9F95D2FACE401](https://user-images.githubusercontent.com/52404201/69026653-b91d2d00-0a06-11ea-9e4c-51cd587be910.png)
APP版本：2.04

**Comment by tracyhenryduck2** [comment]
@fengzehua5

**Comment by fengzehua5** [comment]
颜色已修改，文字已跟随系统语言；但是文字状态说明反了，插座关闭时显示是打开的，APP内开关按钮总是自己跳，基本无法控制插座开或关。 @tracyhenryduck2

**Comment by fengzehua5** [comment]
所有设备离线状态下显示的是“NO”（系统语言是中文）；PIR正常情况显示英文，触发状态显示中文（系统语言是中文）。
![98E2120A8F233B314ABE2F927164B8B0](https://user-images.githubusercontent.com/52404201/69133087-47211280-0af0-11ea-9745-c205f48d8117.png)
![D733C9AE9901C8B3183459D0C78DEFA2](https://user-images.githubusercontent.com/52404201/69133106-5011e400-0af0-11ea-8a9d-755dc6d19202.png)
![6E9B2FBA2A1FF9B3DF6EA872E4985D72](https://user-images.githubusercontent.com/52404201/69133190-7768b100-0af0-11ea-8ec2-56a4e408a4f9.png)

**Comment by fengzehua5** [comment]
@tracyhenryduck2

**Comment by tracyhenryduck2** [comment]
已解决@fengzehua5

**Comment by fengzehua5** [comment]
插座开启和关闭的状态颜色显示要呼唤一下，关闭时为红色，开启时为绿色；其他问题都已解决 @tracyhenryduck2

**Comment by siterwellinfo** [comment]
已解决

**Comment by siterwellinfo** [comment]
@fengzehua5

**Comment by fengzehua5** [comment]
已解决
