### ISSUE TITLE
摄像头添加问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/BASE#3]
同一台摄像机我可以在添加后再次添加
![17BDD9D8F78C5836BC50AD53AED1000E](https://user-images.githubusercontent.com/52404201/69026693-e4078100-0a06-11ea-9a8e-e2ae003881d7.png)
APP版本：2.04

**Comment by tracyhenryduck2** [comment]
已解决@fengzehua5

**Comment by fengzehua5** [comment]
问题没有重现
