### ISSUE TITLE
首页的585按键显示

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/BASE#4]
585按键在首页的图标显示出现bug
![F7296E41F9A37962C26DCDBD6C6B09DA](https://user-images.githubusercontent.com/52404201/69026806-6f811200-0a07-11ea-8af3-5d67d8f5bc57.png)
APP版本：2.04

**Comment by tracyhenryduck2** [comment]
已解决@fengzehua5

**Comment by fengzehua5** [comment]
已验证
