### ISSUE TITLE
登录界面

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/BASE#7]
屏幕上方有黑条；输入完密码后，登录按键被键盘挡住了，点不到；下划一下，如果过头了就会直接进入APP，此时APP内数据是错的
![98C13F7AB12CB8174D21CF3BB374492A](https://user-images.githubusercontent.com/52404201/69134384-5c973c00-0af2-11ea-92e3-8e203d3d9661.png)

**Comment by tracyhenryduck2** [comment]
已解决@fengzehua5

**Comment by fengzehua5** [comment]
已验证
