### ISSUE TITLE
摄像头列表出现不存在的设备

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/BASE#9]
摄像头列表会多出一个不存在的设备，把存在的设备全部删除后这个设备会消失，只添加一个设备后这个不存在的设备就会出现。
![895460031E12020053E90DED3DA9A778](https://user-images.githubusercontent.com/52404201/69200315-b856d900-0b75-11ea-8597-86ad75be62d6.png)

**Comment by tracyhenryduck2** [comment]
已解决 @fengzehua5

**Comment by fengzehua5** [comment]
已验证
